services:
  piquel-api:
    image: ghcr.io/piquelorganization/api.piquel.fr:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.piquel-api.loadbalancer.server.port=80"
      - "traefik.http.routers.piquel-api.rule=Host(`${HOST}`)"
      - "traefik.http.routers.piquel-api.entrypoints=piquel-https"
      - "traefik.http.routers.piquel-api.tls.certresolver=piquel-resolver"
    environment:
      DOMAIN: ${DOMAIN}
      REDIRECT_TO: ${REDIRECT_TO}
      HOST: ${HOST}
      SSL: "true"
      DB_URL: ${DB_URL}
      # Auth
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
      AUTH_GOOGLE_CLIENT_ID: ${AUTH_GOOGLE_CLIENT_ID}
      AUTH_GOOGLE_CLIENT_SECRET: ${AUTH_GOOGLE_CLIENT_SECRET}
      # Cookies
      COOKIES_AUTH_SECRET: ${COOKIES_AUTH_SECRET}
    deploy:
      update_config:
        order: start-first
    networks:
      - piquel-network

networks:
  piquel-network:
    external: true
    name: piquel-network
